// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCgJUw_OrH5KhMtxnnahy6wzXlMgsd7A',
    appId: '1:822257671635:web:1f3dd6e254afab3dd5e326',
    messagingSenderId: '822257671635',
    projectId: 'luckyboba-app',
    authDomain: 'luckyboba-app.firebaseapp.com',
    storageBucket: 'luckyboba-app.firebasestorage.app',
    measurementId: 'G-20QPQSYS4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDthqZboz-V159d9cd0x65Aq862Qej4hvw',
    appId: '1:822257671635:android:4c1ddc8fc33a23f3d5e326',
    messagingSenderId: '822257671635',
    projectId: 'luckyboba-app',
    storageBucket: 'luckyboba-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFktFaWom6OWZJPfrgGNPXiNysl4CbrCU',
    appId: '1:822257671635:ios:806340813cde7444d5e326',
    messagingSenderId: '822257671635',
    projectId: 'luckyboba-app',
    storageBucket: 'luckyboba-app.firebasestorage.app',
    androidClientId: '822257671635-9bq8u2do11r5bqnrk0i0vloriprp5boa.apps.googleusercontent.com',
    iosClientId: '822257671635-nvrqjdonvf3sqoi66a0ldc47jbbdrlub.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckybobaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFktFaWom6OWZJPfrgGNPXiNysl4CbrCU',
    appId: '1:822257671635:ios:806340813cde7444d5e326',
    messagingSenderId: '822257671635',
    projectId: 'luckyboba-app',
    storageBucket: 'luckyboba-app.firebasestorage.app',
    androidClientId: '822257671635-9bq8u2do11r5bqnrk0i0vloriprp5boa.apps.googleusercontent.com',
    iosClientId: '822257671635-nvrqjdonvf3sqoi66a0ldc47jbbdrlub.apps.googleusercontent.com',
    iosBundleId: 'com.example.luckybobaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCgJUw_OrH5KhMtxnnahy6wzXlMgsd7A',
    appId: '1:822257671635:web:67201671aca9b70cd5e326',
    messagingSenderId: '822257671635',
    projectId: 'luckyboba-app',
    authDomain: 'luckyboba-app.firebaseapp.com',
    storageBucket: 'luckyboba-app.firebasestorage.app',
    measurementId: 'G-4JS5BEMENV',
  );
}
